name: semgrep
bin: "tools/semgrep/osemgrep"
default_command: scan-sarif

rules: "tools/semgrep/rules"

commands:
  scan-sarif:
    action: scan
    flags:
      - "--config {rules}"
      - "--sarif-output {output}"
      - "--metrics=off"
      - "--disable-version-check"
      - "{target}"

  scan-json:
    action: scan
    flags:
      - "--config {rules}"
      - "--json {output}"
      - "--metrics=off"
      - "--disable-version-check"
      - "{target}"

  version:
    flags:
      - "--version"

output:
  format: sarif
  dir: "tools/semgrep/res"


